# Практическая работа по СЛАУ
## № 2.10.6 л)

In [105]:
import numpy as np
from math import*

N = 20
A = np.zeros((N, N))
for i in range(N):
    for j in range(N):
        if (i == j):
            A[i,i] = 10.
        else:
            A[i,j] = 1./(i+j+2)

b = np.zeros((N,1))
for i in range(N):
    b[i,0] = 1./(i+1)

inv_A = np.linalg.inv(A)

Найдем числа обусловленности матрицы А:

1. Числа обусловленности по кубической и октаэдрической нормам (будут совпадать, т.к. матрица симметричная):

In [84]:
norm1_A, sum_A = 0, 0
norm1_invA, sum_invA = 0, 0
for i in range(N):
    for j in range(N):
        sum_A += A[i,j]
        sum_invA += inv_A[i,j]
    if sum_A > norm1_A:
        norm1_A = sum_A
    if sum_invA > norm1_invA:
        norm1_invA = sum_invA    
    sum_A = 0
    sum_invA = 0
print 'Число обусловленности: ', norm1_A * norm1_invA

Число обусловленности:  1.1435607239195356


2.Число обусловленности по евклидовой норме:

In [49]:
l1, e1 = np.linalg.eig(A.dot(A))
l_max = np.amax(l1)
l_min = np.amin(l1)
print 'Число обусловленности: ', sqrt(l_max)

Число обусловленности:  11.3001283984


Максимальное и минимальное значения собственных чисел:

In [50]:
lA, eA = np.linalg.eig(A)
l_maxA = np.amax(lA)
l_minA = np.amin(lA)
print 'lambda max: ', l_maxA
print 'lambda min: ', l_minA

lambda max:  11.300128398425871
lambda min:  9.65779712494759


## Метод Гаусса

In [149]:
Ab = np.hstack((A,b))
#Прямой ход метода Гаусса
for k in range(N):
    for j in range(k+1, N+1):
        Ab[k,j] = Ab[k,j]/Ab[k,k]
    Ab[k,k] = 1
    for i in range(k+1, N):
        div = Ab[i,k]
        for j in range(k, N+1):
            Ab[i, j] = Ab[i,j]/div - Ab[k,j]
#Обратный ход метода Гаусса
X = np.zeros((N, 1))
for k in range(N-1, -1, -1):
        X[k] += Ab[k, N]
        for j in range(k-1, -1 -1):
            X[k] -= X[j] * Ab[k,j]

print 'Полученное решение: \n', X

Полученное решение: 
[[0.1       ]
 [0.04671858]
 [0.02996764]
 [0.02186691]
 [0.01712252]
 [0.01401963]
 [0.01183835]
 [0.01022463]
 [0.00898449]
 [0.00800294]
 [0.00720757]
 [0.00655056]
 [0.0059991 ]
 [0.00552995]
 [0.00512616]
 [0.00477514]
 [0.0044673 ]
 [0.00419524]
 [0.00395313]
 [0.00373636]]


Найдем невязку:

In [186]:
delta_X = b - A.dot(X)
print 'Невязка: \n', delta_X
print 'Норма невязки: \n', np.linalg.norm(delta_X, ord=2)

Невязка: 
[[-0.03988409]
 [-0.02131483]
 [-0.01393954]
 [-0.01002162]
 [-0.00760786]
 [-0.00598049]
 [-0.0048147 ]
 [-0.00394236]
 [-0.00326783]
 [-0.00273273]
 [-0.00229946]
 [-0.0019427 ]
 [-0.00164481]
 [-0.00139312]
 [-0.00117829]
 [-0.00099333]
 [-0.00083285]
 [-0.00069268]
 [-0.00056951]
 [-0.00046071]]
Норма невязки: 
0.05008108715464271


## Метод Зейделя

In [189]:
D = np.zeros((N,N))
for i in range(N):
    D[i,i] = A[i,i]
L = np.zeros((N,N))
for i in range(N):
    for j in range(i):
        L[i,j] = A[i,j]
U = A - D - L
R = -1 * np.dot(np.linalg.inv(L+D), U)
F = np.dot(np.linalg.inv(L+D), b)
eps = 10 ** (-6)

X_s = np.zeros((N,1))
X_s1 = np.zeros((N,1))
k = 0
while (True):
    X_s = X_s1
    X_s1 = np.dot(R, X_s) + F
    k += 1
    if (np.linalg.norm((X_s - X_s1), ord=2) < eps): 
        break     
print 'Полученное решение: \n', X_s1
print 'Решение получено за ', k, 'итераций'

Полученное решение: 
[[0.09615746]
 [0.04478375]
 [0.02874755]
 [0.02101576]
 [0.01649429]
 [0.01353947]
 [0.01146294]
 [0.00992677]
 [0.00874602]
 [0.00781115]
 [0.00705327]
 [0.00642689]
 [0.0059008 ]
 [0.00545292]
 [0.00506717]
 [0.00473155]
 [0.00443698]
 [0.00417641]
 [0.00394434]
 [0.00373636]]
Решение получено за  5 итераций


Критерием остановки процесса является условие:
$||x_{s+1}-x_{s}|| < \epsilon$, где $\epsilon = 10 ^{-6}$

Найдем невязку для метода Зейделя:

In [187]:
delta_X1 = b - A.dot(X_s1)
print 'Невязка: \n', delta_X1
print 'Норма невязки: \n', np.linalg.norm(delta_X1, ord=2)

Невязка: 
[[ 1.04319222e-08]
 [ 6.36054964e-09]
 [ 3.78309040e-09]
 [ 2.29603972e-09]
 [ 1.41782144e-09]
 [ 8.83678047e-10]
 [ 5.51064333e-10]
 [ 3.40532796e-10]
 [ 2.06042364e-10]
 [ 1.19964538e-10]
 [ 6.52240900e-11]
 [ 3.10073495e-11]
 [ 1.03284464e-11]
 [-1.39771528e-12]
 [-7.21779581e-12]
 [-9.17405041e-12]
 [-8.64298216e-12]
 [-6.55406979e-12]
 [-3.53349988e-12]
 [ 0.00000000e+00]]
Норма невязки: 
1.3120150107138125e-08
